CREATE TABLE "GCG_5822_ROUTER_LINES" (
 "PART_WC" CHAR(21),
 "DESCRIPTION" CHAR(100),
 "QUANTITY" NUMERIC(12,6),
 "UOM" CHAR(2),
 "RATE_PRICE" NUMERIC(12,6),
 "LINE_ROUTER" CHAR(6),
 "Router" CHAR(20),
 "EXT_DESC" varchar(4000) );